### ISSUE TITLE
Duplicate prefix removal issue (apx)

### ISSUE THREAD

**Issue by Nixtren** [psvz/tirexASN#1]
It seems the following command also removes some IP ranges:
```
uniq -f 1 map >apx
grep 8.8.8.0/24 apx
 - No results
````
Doing uniq -f 0 seems to fix the problem:
```
uniq -f 0 map >apx
grep 8.8.8.0/24 apx
8.8.8.0/24      15169
```
However, then some duplicate ranges appear:
```
grep 84.205.80.0/24 apx
84.205.80.0/24  12654
84.205.80.0/24              # Notice the missing AS number here, bug?
```
I guess we need a more reliable way to remove duplicates, without removing some IP ranges by "mistake" (such as 8.8.8.0/24).

**Comment by psvz** [comment]
This is expected behavior. We do NOT have CIDR format in apx file, i.e.
```
# grep 8.8.8.0 apx
15169   8.8.8.0
```
and
```
# grep '/' apx
- No results
```
This is due to redundancy of network mask (i.e. /24) for our binary search.
